#!/bin/sh	

if [ ! -d "bin" ]; then
	mkdir bin;
fi
if [ ! -d "hex" ]; then
	mkdir hex;
fi

avr-gcc -Os -DF_CPU=16000000UL -I./inc -mmcu=atmega328p $1.c adc.c hserial.c handlers.c interruptions.c -o ./bin/$1
avr-objcopy -O ihex -R .eeprom ./bin/$1 ./hex/$1.hex
#avrdude -F -V -c arduino -p ATMEGA328P -P /dev/ttyUSB0 -b 115200 -U flash:w:$1.hex #UNO
avrdude -F -V -c arduino -p ATMEGA328P -P $2 -b 57600 -U flash:w:./hex/$1.hex #DUEMILINOVA
